blank_issues_enabled: false # 不允许用户创建空白 Issue
contact_links:
  - name: 遇到问题先去看文档！谢谢！ # 外部网站名称
    url: https://gitee.com/inrgihc/sqlrest/blob/master/README.md # 跳转的外部网站目标地址
    about: 文档可以解决你百分之八九十的疑惑 # 跳转外部网站的描述说明
